name: MemAttacker-And-MemRanger-Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2016

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.0.3
      - name: Install Windows Driver Kit
        run: choco install windowsdriverkit10
      - name: Find files
        run: |
          Get-ChildItem -Path "C:\Program Files (x86)\Windows Kits\10\Include\" -Recurse
      - name: msbuild-MemAttacker
        working-directory: MemAttacker
        run: msbuild /property:Configuration=Release /p:PlatformToolset=v141 /p:IncludePath='C:\Program Files (x86)\Windows Kits\10\INclude\10.0.19041.685\km\'
      - name: msbuild-MemRanger
        working-directory: MemRanger
        run: msbuild /property:Configuration=Release /p:PlatformToolset=v141 /p:IncludePath='C:\Program Files (x86)\Windows Kits\10\INclude\10.0.19041.685\km\'
      - name: Create Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: Release ${{ github.sha }}
          files: ./x64/Release/MemAttacker.exe
          prerelease: false
