name: MemoryRanger-Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2016

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.0.3
      - name: msbuild
        working-directory: MemRanger
        run: msbuild /property:Configuration=Release /p:PlatformToolset=v141
      - name: Create Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: Memory Ranger - Release ${{ github.sha }}
          files: ./x64/Release/MemRanger.exe
          prerelease: false
